# Generated by Django 3.1.5 on 2021-05-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('pgn', models.CharField(blank=True, max_length=10000, null=True)),
                ('time_class', models.CharField(blank=True, max_length=50, null=True)),
                ('white_rating', models.IntegerField(blank=True, null=True)),
                ('white_result', models.CharField(blank=True, max_length=50, null=True)),
                ('black_rating', models.IntegerField(blank=True, null=True)),
                ('black_result', models.CharField(blank=True, max_length=50, null=True)),
                ('black_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='all_chess_games.chessplayer')),
                ('white_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='all_chess_games.chessplayer')),
            ],
        ),
    ]
